CREATE TABLE `t_order` (
    `id`            BIGINT         NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_no`      VARCHAR(30)    NOT NULL COMMENT '订单号',
    `employee_id`   BIGINT         NOT NULL COMMENT '员工ID',
    `product_id`    BIGINT         NOT NULL COMMENT '商品ID',
    `product_name`  VARCHAR(200)   NOT NULL COMMENT '商品名称',
    `product_image` VARCHAR(500)            DEFAULT NULL COMMENT '商品图片',
    `points_cost`   DECIMAL(12,2)  NOT NULL COMMENT '单价积分',
    `quantity`      INT            NOT NULL DEFAULT 1 COMMENT '数量',
    `total_points`  DECIMAL(12,2)  NOT NULL COMMENT '总积分',
    `status`        VARCHAR(20)    NOT NULL DEFAULT 'PENDING' COMMENT '订单状态: PENDING/TO_SHIP/SHIPPED/COMPLETED/CANCELLED',
    `remark`        VARCHAR(500)            DEFAULT NULL COMMENT '备注',
    `created_at`    DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`    DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `created_by`    BIGINT                  DEFAULT NULL COMMENT '创建人',
    `updated_by`    BIGINT                  DEFAULT NULL COMMENT '更新人',
    `deleted`       TINYINT        NOT NULL DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    `version`       INT            NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_order_no` (`order_no`),
    INDEX `idx_employee_id` (`employee_id`),
    INDEX `idx_status` (`status`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '订单表';
